### ISSUE TITLE
The ".bin" extension file is missing./Marlin-bugfix-2.0.x-EnderExtender

### ISSUE THREAD

**Issue by plevia** [enderextender/FirmwareReleases#4]
Since the ".bin" extension file does not exist, it cannot be converted to Firmware and cannot be updated.
For reference, I changed the ".h" extension such as "Configuration.h" and "Configuration_adv.h" to a ".bin" file. And when I copied it to an SD card and loaded it into ender3pro, it didn't start.
Also, if you open it with "Visual Studio Code" and click "Platform IO: Build", there will be an error.

**Comment by enderextender** [comment]
I’ve found that the latest version of marlin is not working well with the BTT E3 Mini V2 board so I have switched to using the Bigtreetech version.  I’m testing this now and will upload the bin files soon.

 

This is a very time consuming process.

 

 

 

Regards,

Mark Williamson

Ender Extender Support

 

From: plevia ***@***.***> 
Sent: Thursday, April 29, 2021 7:21 AM
To: enderextender/FirmwareReleases ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [enderextender/FirmwareReleases] There is an error. Unable to compile.　　Marlin-bugfix-2.0.x-EnderExtender (#4)

 

"Configuration_adv.h", "Configuration_adv.h", "Statusscreen.h", and "Bootscreen.h" all had errors and could not be compiled.
As an amateur, I can't fix it.
There were 59 error.
I am in great trouble because I cannot solve the problem after purchasing the kit.
Please update the changed version.

**Comment by plevia** [comment]
Hello,
Thank you for the quick response.
The data uploaded 11 hours ago says "The mini firmware is being updated again". Has that data been tested and modified? If it has been fixed, it has not been improved. It's a problem that doesn't change.
Or did you just switch to the "Bigtreetech version"?
I'm currently unable to use my 3D printer, so I'm hoping you can upload a firmware that has no problems at an early stage.
Thank you,

**Comment by enderextender** [comment]
Yes i tested it today . It is fully functional

Regards,
Mark Williamson

**Comment by plevia** [comment]
![1](https://user-images.githubusercontent.com/83106796/116706120-3b858b00-aa08-11eb-86ae-9f55fdc78b90.jpg)
![2](https://user-images.githubusercontent.com/83106796/116706149-417b6c00-aa08-11eb-973d-233d5e5334fc.jpg)
![3](https://user-images.githubusercontent.com/83106796/116706153-42ac9900-aa08-11eb-8166-db5bfac7cc97.jpg)
Hello,
I'm sorry many times.
Load "platformio.ini" and "Configuration.h" with Visual Studio Code and click "platformIO: Bild", but there is an error as shown in the picture and firmware cannot be created (.bin file cannot be created).
Please point out my mistake.
Also, please tell me how to create it.

**Comment by enderextender** [comment]
Try this

 



 

 

Regards,

Mark Williamson

Ender Extender Support

**Comment by plevia** [comment]
Hello,
It says "Try this", what should I try? 
Please reply.

**Comment by plevia** [comment]
If you need to update the firmware and don't know how to do it, please learn the process before you make this kit. And then, Ender Extender is a great product. And "Ender Extender is not responsible for the ability or lack of ability to update the firmware on your machine." It is stated that I know it's subjective, but you could at least tell me where to fix it in Visual Studio code.

**Comment by plevia** [comment]
The content on the Ender Extender home page requires a firmware update, and if you don't know how to do this, learn the process before creating this kit. Also, Ender Extender states that it is not responsible for the ability to update the machine's firmware, but my subjective opinion could be to tell me where to fix the Visual Studio code.
Will you support me that much?

**Comment by enderextender** [comment]
Yes these are because you are missing libraries

Would you be available tonight or tomorrow for online meeting?

Right now it is 4:00 pm in my time zone. I will be available tonight from 8pm to 11pm cst or tomorrow 

Regards,
Mark Williamson

**Comment by enderextender** [comment]
> Since the ".bin" extension file does not exist, it cannot be converted to Firmware and cannot be updated. For reference, I changed the ".h" extension such as "Configuration.h" and "Configuration_adv.h" to a ".bin" file. And when I copied it to an SD card and loaded it into ender3pro, it didn't start. Also, if you open it with "Visual Studio Code" and click "Platform IO: Build", there will be an error.

Totally the wrong thing to be doing.  that's why it's not working.

**Comment by enderextender** [comment]
Closing.
